export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  API_ERROR = "API_ERROR",

  MISSING_INIT_DATA_ERROR = "MISSING_INIT_DATA_ERROR",
  INIT_DATA_ERROR = "INIT_DATA_ERROR",
  MISSING_USER_ID_ERROR = "MISSING_USER_ID_ERROR",
  MISSING_USER_TOKEN_ERROR = "MISSING_USER_TOKEN_ERROR",
  AUTH_ERROR = "AUTH_ERROR",
}
