export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  MISSING_INIT_DATA_ERROR: "MISSING_INIT_DATA_ERROR",
  INIT_DATA_ERROR: "INIT_DATA_ERROR",
  NOT_FOUND: "NOT_FOUND",
  TELEGRAM_UPSTREAM_ERROR: "TELEGRAM_UPSTREAM_ERROR",
  UPSTREAM_HTTP_ERROR: "UPSTREAM_HTTP_ERROR",
  UPSTREAM_TIMEOUT_ERROR: "UPSTREAM_TIMEOUT_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
