// currencies.ts

export const CURRENCIES = [
  { code: "AFN", name: "Afghan Afghani", flag: "🇦🇫" },
  { code: "ALL", name: "Albanian Lek", flag: "🇦🇱" },
  { code: "DZD", name: "Algerian Dinar", flag: "🇩🇿" },
  { code: "ARS", name: "Argentine Peso", flag: "🇦🇷" },
  { code: "AMD", name: "Armenian Dram", flag: "🇦🇲" },
  { code: "AUD", name: "Australian Dollar", flag: "🇦🇺" },
  { code: "AZN", name: "Azerbaijani Manat", flag: "🇦🇿" },
  { code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩" },
  { code: "BYN", name: "Belarusian Ruble", flag: "🇧🇾" },
  { code: "BOB", name: "Bolivian Boliviano", flag: "🇧🇴" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", flag: "🇧🇦" },
  { code: "BRL", name: "Brazilian Real", flag: "🇧🇷" },
  { code: "GBP", name: "British Pound", flag: "🇬🇧" },
  { code: "BND", name: "Brunei Dollar", flag: "🇧🇳" },
  { code: "BGN", name: "Bulgarian Lev", flag: "🇧🇬" },
  { code: "CAD", name: "Canadian Dollar", flag: "🇨🇦" },
  { code: "CLP", name: "Chilean Peso", flag: "🇨🇱" },
  { code: "CNY", name: "Chinese Yuan", flag: "🇨🇳" },
  { code: "COP", name: "Colombian Peso", flag: "🇨🇴" },
  { code: "CRC", name: "Costa Rican Colón", flag: "🇨🇷" },
  { code: "HRK", name: "Croatian Kuna", flag: "🇭🇷" },
  { code: "CZK", name: "Czech Koruna", flag: "🇨🇿" },
  { code: "DKK", name: "Danish Krone", flag: "🇩🇰" },
  { code: "DOP", name: "Dominican Peso", flag: "🇩🇴" },
  { code: "EGP", name: "Egyptian Pound", flag: "🇪🇬" },
  { code: "ETB", name: "Ethiopian Birr", flag: "🇪🇹" },
  { code: "EUR", name: "Euro", flag: "🇪🇺" },
  { code: "GEL", name: "Georgian Lari", flag: "🇬🇪" },
  { code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭" },
  { code: "GTQ", name: "Guatemalan Quetzal", flag: "🇬🇹" },
  { code: "HNL", name: "Honduran Lempira", flag: "🇭🇳" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "🇭🇰" },
  { code: "HUF", name: "Hungarian Forint", flag: "🇭🇺" },
  { code: "ISK", name: "Icelandic Króna", flag: "🇮🇸" },
  { code: "INR", name: "Indian Rupee", flag: "🇮🇳" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩" },
  { code: "IRR", name: "Iranian Rial", flag: "🇮🇷" },
  { code: "IQD", name: "Iraqi Dinar", flag: "🇮🇶" },
  { code: "ILS", name: "Israeli New Shekel", flag: "🇮🇱" },
  { code: "JMD", name: "Jamaican Dollar", flag: "🇯🇲" },
  { code: "JPY", name: "Japanese Yen", flag: "🇯🇵" },
  { code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴" },
  { code: "KZT", name: "Kazakhstani Tenge", flag: "🇰🇿" },
  { code: "KES", name: "Kenyan Shilling", flag: "🇰🇪" },
  { code: "KGS", name: "Kyrgystani Som", flag: "🇰🇬" },
  { code: "LBP", name: "Lebanese Pound", flag: "🇱🇧" },
  { code: "MOP", name: "Macanese Pataca", flag: "🇲🇴" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾" },
  { code: "MVR", name: "Maldivian Rufiyaa", flag: "🇲🇻" },
  { code: "MUR", name: "Mauritian Rupee", flag: "🇲🇺" },
  { code: "MXN", name: "Mexican Peso", flag: "🇲🇽" },
  { code: "MDL", name: "Moldovan Leu", flag: "🇲🇩" },
  { code: "MNT", name: "Mongolian Tugrik", flag: "🇲🇳" },
  { code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦" },
  { code: "MZN", name: "Mozambican Metical", flag: "🇲🇿" },
  { code: "MMK", name: "Myanmar Kyat", flag: "🇲🇲" },
  { code: "NPR", name: "Nepalese Rupee", flag: "🇳🇵" },
  { code: "TWD", name: "New Taiwan Dollar", flag: "🇹🇼" },
  { code: "NZD", name: "New Zealand Dollar", flag: "🇳🇿" },
  { code: "NIO", name: "Nicaraguan Córdoba", flag: "🇳🇮" },
  { code: "NGN", name: "Nigerian Naira", flag: "🇳🇬" },
  { code: "NOK", name: "Norwegian Krone", flag: "🇳🇴" },
  { code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰" },
  { code: "PAB", name: "Panamanian Balboa", flag: "🇵🇦" },
  { code: "PYG", name: "Paraguayan Guarani", flag: "🇵🇾" },
  { code: "PEN", name: "Peruvian Sol", flag: "🇵🇪" },
  { code: "PHP", name: "Philippine Peso", flag: "🇵🇭" },
  { code: "PLN", name: "Polish Złoty", flag: "🇵🇱" },
  { code: "QAR", name: "Qatari Riyal", flag: "🇶🇦" },
  { code: "RON", name: "Romanian Leu", flag: "🇷🇴" },
  { code: "RUB", name: "Russian Ruble", flag: "🇷🇺" },
  { code: "SAR", name: "Saudi Riyal", flag: "🇸🇦" },
  { code: "RSD", name: "Serbian Dinar", flag: "🇷🇸" },
  { code: "SGD", name: "Singapore Dollar", flag: "🇸🇬" },
  { code: "ZAR", name: "South African Rand", flag: "🇿🇦" },
  { code: "KRW", name: "South Korean Won", flag: "🇰🇷" },
  { code: "LKR", name: "Sri Lankan Rupee", flag: "🇱🇰" },
  { code: "SEK", name: "Swedish Krona", flag: "🇸🇪" },
  { code: "CHF", name: "Swiss Franc", flag: "🇨🇭" },
  { code: "SYP", name: "Syrian Pound", flag: "🇸🇾" },
  { code: "TJS", name: "Tajikistani Somoni", flag: "🇹🇯" },
  { code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿" },
  { code: "THB", name: "Thai Baht", flag: "🇹🇭" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", flag: "🇹🇹" },
  { code: "TRY", name: "Turkish Lira", flag: "🇹🇷" },
  { code: "AED", name: "UAE Dirham", flag: "🇦🇪" },
  { code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬" },
  { code: "UAH", name: "Ukrainian Hryvnia", flag: "🇺🇦" },
  { code: "UYU", name: "Uruguayan Peso", flag: "🇺🇾" },
  { code: "USD", name: "US Dollar", flag: "🇺🇸" },
  { code: "UZS", name: "Uzbekistani Som", flag: "🇺🇿" },
  { code: "VND", name: "Vietnamese Dong", flag: "🇻🇳" },
  { code: "YER", name: "Yemeni Rial", flag: "🇾🇪" },
] as const;

export const CURRENCY_CODES = CURRENCIES.map((c) => c.code);

export type CurrencyCode = (typeof CURRENCIES)[number]["code"];
